#!/bin/bash
workDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# places
cd $workDir/places/1024
ln -s folder-home.png bookmark-missing-drag-accept.png
ln -s folder-html.png bookmark-missing-drag-accept.png
ln -s folder-html.png bookmark-missing-open.png
ln -s folder-html.png bookmark-missing.png
ln -s user-trash-full.png edittrash.png
ln -s user-trash.png emptytrash.png
ln -s folder-public.png folder-cloud.png
ln -s desktop.png folder-desktop-drag-accept.png
ln -s desktop.png folder-desktop-open.png
ln -s desktop.png folder-desktop.png
ln -s folder-download.png folder-download-drag-accept.png
ln -s folder-download.png folder-download-open.png
ln -s folder-download.png folder-downloads.png
ln -s folder.png folder-fs-directory.png
ln -s folder.png folder-games.png
ln -s folder.png folder-github.png
ln -s folder-pictures.png folder-image-open.png
ln -s folder-pictures.png folder-image.png
ln -s folder-pictures.png folder-images.png
ln -s folder.png folder-mega.png
ln -s folder-music.png folder-music-drag-accept.png
ln -s folder-music.png folder-music-open.png
ln -s folder-public.png folder-onedrive.png
ln -s folder-public.png folder-owncloud.png
ln -s folder-pictures.png folder-pictures-drag-accept.png
ln -s folder-public.png folder-public-html.png
ln -s folder-public.png folder-publicshare.png
ln -s folder.png folder-recent.png
ln -s network_fs.png folder-remote-ftp.png
ln -s network_fs.png folder-remote-nfs.png
ln -s network_fs.png folder-remote-smb.png
ln -s network_fs.png folder-remote-ssh.png
ln -s folder-saved-search.png application-x-gnome-saved-search.png
ln -s folder-music.png folder-sound.png
ln -s folder.png folder-steam.png
ln -s folder.png folder-templates.png
ln -s folder.png folder-vbox.png
ln -s folder-videos.png folder-videos-drag-accept.png
ln -s folder-videos.png folder-videos-open.png
ln -s folder.png folder-wine.png
ln -s desktop.png gnome-ccdesktop.png
ln -s desktop.png gnome-desktop.png
ln -s desktop.png gnome-destop-config.png
ln -s folder.png gnome-folder.png
ln -s ../../devices/1024/drive-harddisk.png gnome-fs-blockdev.png
ln -s folder-html.png gnome-fs-bookmark-missing.png
ln -s folder-html.png gnome-fs-bookmark.png
ln -s desktop.png gnome-fs-desktop.png
ln -s folder.png gnome-fs-directory-accept
ln -s folder.png gnome-fs-directory-accept.png
ln -s folder.png gnome-fs-directory.png
ln -s network_fs.png gnome-fs-ftp.png
ln -s folder-home.png gnome-fs-gnome.png
ln -s folder-home.png gnome-fs-home.png
ln -s network_fs.png gnome-fs-network.png
ln -s network_fs.png gnome-fs-nfs.png
ln -s network_fs.png gnome-fs-share.png
ln -s network_fs.png gnome-fs-smb.png
ln -s network_fs.png gnome-fs-ssh.png
ln -s user-trash-full.png gnome-fs-trash-empty-accept.png
ln -s user-trash.png gnome-fs-trash-empty.png
ln -s user-trash-full.png gnome-fs-trash-full.png
ln -s folder-home.png gnome-home.png
ln -s network_fs.png gnome-mime-x-directory-share.png
ln -s network_fs.png gnome-mime-x-directory-smb-share.png
ln -s network_fs.png gnome-mime-x-directory-smb-workgroup.png
ln -s user-trash-full.png gnome-stock-trash-full.png
ln -s folder-home.png gnome-stock-trash.png
ln -s folder.png gtk-directory.png
ln -s network_fs.png gtk-network.png
ln -s folder.png inode-directory.png
ln -s folder-music.png library-music.png
ln -s network_fs.png neat.png
ln -s network_fs.png network_local.png
ln -s network_fs.png network-workgroup.png
ln -s network_fs.png network.png
ln -s desktop.png other-desktop.png
ln -s network_fs.png redhat-system-group.png
ln -s folder.png stock_folder.png
ln -s folder-public.png  stock_shared-by-me.png
ln -s folder-remote.pngstock_shared-to-me.png
ln -s user-trash-full.png stock_trash_full.png
ln -s user-trash.png trashcan_empty.png
ln -s user-trash-full.png trashcan_full.png
ln -s folder-html.png user-bookmarks.png
ln -s desktop.png user-desktop.png
ln -s folder-pictures.png user-images.png
ln -s folder-pictures.png user-pictures.png
ln -s folder-public.png user-share.png
ln -s user-trash-full.png user-trash-full-symbolic.png
ln -s user-trash.png user-trash-symbolic.png
ln -s user-trash.png xfce-trash_empty.svg
ln -s user-trash-full.png xfce-trash_full.svg

# devices
cd $workDir/devices/1024

ln -s drive-harddisk.png block-device.png
ln -s media-optical.png cdrom_unmount.png
ln -s media-optical.png cdwriter_unmount.png
ln -s drive-harddisk.png disk.png
ln -s drive-optical.png drive-cdrom.png
ln -s drive-harddisk.png drive-harddisk-root.png
ln -s drive-harddisk.png drive-harddisk-scsi.png
ln -s drive-harddisk.png drive-harddisk-system.png
ln -s drive-harddisk.png drive-multidisk.png
ln -s drive-removable-media.png drive-removable-media-usb-pendrive.png
ln -s drive-removable-media-usb.png drive-removable-usb.png
ln -s drive-optical.png dvd_unmount.png
ln -s media-optical.png media-optical-dvd.png
ln -s media-optical.png media-optical-audio.png
ln -s media-optical.png media-optical-bd.png
ln -s media-optical.png media-optical-cd.png
ln -s media-optical.png gnome-cd.png
ln -s media-optical.png gnome-dev-cdrom-audio.png
ln -s media-optical.png gnome-dev-cdrom.png
ln -s media-optical.png gnome-dev-disc-audio.png
ln -s media-optical.png gnome-dev-disc-cdr.png
ln -s media-optical.png gnome-dev-disc-cdrom.png
ln -s media-optical.png gnome-dev-disc-dvdram.png
ln -s media-optical.png gnome-dev-disc-dvdrom.png
ln -s media-optical.png gnome-dev-disc-dvdrw.png
ln -s media-optical.png gnome-dev-dvd-alt.png
ln -s media-optical.png gnome-dev-dvd.png
ln -s drive-harddisk.png gnome-dev-flashdisk.png
ln -s drive-harddisk.png gnome-dev-flashkey.png
ln -s drive-harddisk-ieee1394.png gnome-dev-harddisk-1394.png
ln -s drive-harddisk-usb.png gnome-dev-harddisk-usb.png
ln -s drive-harddisk.png gnome-dev-harddisk.png
ln -s drive-harddisk-usb.png gnome-dev-removable-usb.png
ln -s drive-removable-media.png gnome-dev-removable.png
ln -s drive-harddisk-usb.png gnome-dev-unknown-usb.png
ln -s media-optical.png gtk-cdrom.png
ln -s drive-harddisk.png gtk-harddisk.png
ln -s drive-harddisk.png harddisk.png
ln -s drive-harddisk.png harddrive.png
ln -s drive-harddisk.png hdd_unmount.png
ln -s media-optical.png media-cdr.png
ln -s media-optical.png media-cdrom-audio.png
ln -s media-optical.png media-cdrom.png
ln -s media-optical.png media-dvd.png
ln -s media-optical.png media-dvdrw.png
ln -s media-optical.png media-optical-audio.png
ln -s media-optical.png media-optical-blu-ray.png
ln -s media-optical.png media-optical-cd-r.png
ln -s media-optical.png media-optical-cd-video.png
ln -s media-optical.png media-optical-cd.png
ln -s media-optical.png media-optical-cdr.png
ln -s media-optical.png media-optical-data.png
ln -s media-optical.png media-optical-dvd-ram.png
ln -s media-optical.png media-optical-dvd-rom.png
ln -s media-optical.png media-optical-dvd-rw.png
ln -s media-optical.png media-optical-dvd-video.png
ln -s media-optical.png media-optical-dvd.png
ln -s media-optical.png media-optical-mixed-cd.png
ln -s media-optical.png media-optical-recordable.png
ln -s media-optical.png media-optical-video.png
ln -s drive-removable-media.png media-removable.png
ln -s drive-removable-media.png unity-fallback-mount-helper.png
ln -s drive-removable-media.png usbpendrive_unmount.png
ln -s drive-harddisk.png yast_HD.png
ln -s drive-harddisk.png yast_idetude.png






